[package]
name = "dyn_fs"
version = "0.0.1"
edition = "2021"
authors = ["alshdavid"]
repository = "https://github.com/alshdavid/dyn-fs"
description = "Abstraction for the std::fs stdlib"
license = "MIT"

[lib]

[dependencies]
normalize-path = "^0.2"
