[package]
name = "ifilesystem"
version = "0.1.0"
edition = "2021"
authors = ["alshdavid"]
repository = "https://github.com/alshdavid/ifilesystem"
description = "Bundler For The Modern Web"
license = "MIT"

[dependencies]
normalize-path = "0.2"
